version: '3.8'
services:
  context-catalog:
    image: halverneus/static-file-server
    hostname: context-catalog
    container_name: context-catalog
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./docker/context-catalog:/web 

  postgres:
    image: postgis/postgis
    hostname: postgres
    container_name: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "ngb", "-U", "ngb"]
      interval: 10s
      timeout: 5s
      retries: 5

  scorpio:
    image: scorpiobroker/all-in-one-runner:java-latest
    hostname: scorpio
    container_name: scorpio
    expose:
      - "9090"
    ports:
      - "9090:9090"
    depends_on:
      postgres:
        condition: service_healthy
      context-catalog:
        condition: service_started

  fake-goflow2-collector-throughput:
    build:
       context: ./docker/fake-goflow2-collector-throughput
       dockerfile: Dockerfile
    hostname: fake-goflow2-collector-throughput
    container_name: fake-goflow2-collector-throughput
    command: ["python3", "-u", "/opt/fake-goflow2-collector-throughput/goflow2-collector-kafka-throughput.py"]
    volumes:
      - ./docker/fake-goflow2-collector-throughput:/opt/fake-goflow2-collector-throughput
    depends_on:
      netflow-json-parser-throughput-instantiation:
        condition: service_started
      kafka:
        condition: service_healthy

  kafka:
    image: wurstmeister/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_DIRS: "/tmp/kafka-logs"
      KAFKA_CREATE_TOPICS: "network-flows:1:1,netflow-driver-output:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    logging:
      driver: none
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181"
    logging:
      driver: none

  netflow-json-parser-throughput-instantiation:
    build:
      context: .
      dockerfile: ./docker/netflow-json-parser-with-ngsi-ld-instantiator-simple-fake-throughput-instantiation/Dockerfile
    hostname: netflow-json-parser-throughput-instantiation
    container_name: netflow-json-parser-throughput-instantiation
    volumes:
      - ./docker/netflow-json-parser-with-ngsi-ld-instantiator-simple-fake-throughput-instantiation:/opt/netflow-json-parser-with-ngsi-ld-instantiator-simple-fake
    healthcheck:
      test: ["CMD", "python3", "--version"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      scorpio:
        condition: service_started
      context-catalog:
        condition: service_started
      kafka:
        condition: service_healthy
    restart: always