# coding: utf-8

"""
    OpenAPI schemas for YANG data models ngsi-ld-api.yaml, ietf-yang-types@2013-07-15.yang, srl_nokia-bridge-table-mac-duplication.yang, srl_nokia-bridge-table-mac-learning.yang, srl_nokia-bridge-table-mac-limit.yang, srl_nokia-bridge-table-shg.yang, srl_nokia-bridge-table.yang, srl_nokia-common.yang, srl_nokia-connection-point-pseudowires.yang, srl_nokia-extensions.yang, srl_nokia-features.yang, srl_nokia-flexible-algorithms-types.yang, srl_nokia-icmp.yang, srl_nokia-if-ip.yang, srl_nokia-interfaces-bridge-table.yang, srl_nokia-interfaces.yang, srl_nokia-ip-route-tables.yang, srl_nokia-isis-lsdb-types.yang, srl_nokia-isis-lsdb.yang, srl_nokia-isis-types.yang, srl_nokia-keychains.yang, srl_nokia-linux@2019-11-30.yang, srl_nokia-lldp-types.yang, srl_nokia-lldp.yang, srl_nokia-load-balancing.yang, srl_nokia-network-instance.yang, srl_nokia-next-hop-groups.yang, srl_nokia-ospf@2020-12-31.yang, srl_nokia-ospf-lsdb.yang, srl_nokia-ospf-types.yang, srl_nokia-ospfv3-lsas.yang, srl_nokia-platform-control-fp.yang, srl_nokia-platform-control.yang, srl_nokia-platform-lc.yang, srl_nokia-platform-linecard-fib.yang, srl_nokia-platform-pipeline-counters.yang, srl_nokia-platform.yang, srl_nokia-policy-types.yang, srl_nokia-protection-policies.yang, srl_nokia-pw-tunnel.yang, srl_nokia-routing-policy.yang, srl_nokia-srv6-types.yang, srl_nokia-srv6.yang, srl_nokia-static-routes@2019-11-30.yang, srl_nokia-system.yang, srl_nokia-tcp-udp.yang, srl_nokia-traffic-engineering.yang, srl_nokia-tunnel.yang.

    OpenAPI schemas for YANG data models compliant with the NGSI-LD OAS V1.6.1 metamodel according to ETSI GS CIM 009 V1.6.1.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ngsi_ld_models.models.network_instance_protocols_ospf_instance import NetworkInstanceProtocolsOspfInstance

class TestNetworkInstanceProtocolsOspfInstance(unittest.TestCase):
    """NetworkInstanceProtocolsOspfInstance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NetworkInstanceProtocolsOspfInstance:
        """Test NetworkInstanceProtocolsOspfInstance
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NetworkInstanceProtocolsOspfInstance`
        """
        model = NetworkInstanceProtocolsOspfInstance()
        if include_optional:
            return NetworkInstanceProtocolsOspfInstance(
                id = '',
                type = 'NetworkInstanceProtocolsOspfInstance',
                scope = None,
                location = {
                    'key' : null
                    },
                observation_space = {
                    'key' : null
                    },
                operation_space = {
                    'key' : null
                    },
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                modified_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = None,
                admin_state = None,
                version = None,
                address_family = None,
                instance_id = None,
                router_id = None,
                max_ecmp_paths = None,
                advertise_router_capability = None,
                export_policy = None,
                external_preference = None,
                reference_bandwidth = None,
                preference = None,
                oper_state = None,
                last_disabled_reason = None,
                area_border_router = None,
                as_border_router = None,
                backbone_router = None,
                overload_state = None,
                overload_rem_interval = None,
                last_overload_entered_time = None,
                last_overload_exit_time = None,
                last_overload_enter_code = None,
                last_overload_exit_code = None,
                overflow = None,
                last_overflow_entered_time = None,
                last_overflow_exit_time = None,
                opaque_lsa_support = None,
                last_enabled_time = None,
                routes_submitted = None,
                total_exported_routes = None,
                ovld_lsa_limit_rem_interval = None,
                new_lsas_originated = None,
                new_lsas_received = None,
                extern_lsa_count = None,
                extern_lsa_cksum_sum = None,
                is_part_of = None
            )
        else:
            return NetworkInstanceProtocolsOspfInstance(
                type = 'NetworkInstanceProtocolsOspfInstance',
                version = None,
                is_part_of = None,
        )
        """

    def testNetworkInstanceProtocolsOspfInstance(self):
        """Test NetworkInstanceProtocolsOspfInstance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
