# coding: utf-8

"""
    OpenAPI schemas for YANG data models --candil-openapi-schemas-generator-url, ngsi-ld-api.yaml, ietf-yang-types@2013-07-15.yang, srl_nokia-bridge-table-mac-duplication.yang, srl_nokia-bridge-table-mac-learning.yang, srl_nokia-bridge-table-mac-limit.yang, srl_nokia-bridge-table-shg.yang, srl_nokia-bridge-table.yang, srl_nokia-common.yang, srl_nokia-connection-point-pseudowires.yang, srl_nokia-extensions.yang, srl_nokia-features.yang, srl_nokia-flexible-algorithms-types.yang, srl_nokia-icmp.yang, srl_nokia-if-ip.yang, srl_nokia-interfaces-bridge-table.yang, srl_nokia-interfaces.yang, srl_nokia-ip-route-tables.yang, srl_nokia-isis-lsdb-types.yang, srl_nokia-isis-lsdb.yang, srl_nokia-isis-types.yang, srl_nokia-keychains.yang, srl_nokia-linux@2019-11-30.yang, srl_nokia-lldp-types.yang, srl_nokia-lldp.yang, srl_nokia-load-balancing.yang, srl_nokia-network-instance.yang, srl_nokia-next-hop-groups.yang, srl_nokia-ospf@2020-12-31.yang, srl_nokia-ospf-lsdb.yang, srl_nokia-ospf-types.yang, srl_nokia-ospfv3-lsas.yang, srl_nokia-platform-control-fp.yang, srl_nokia-platform-control.yang, srl_nokia-platform-lc.yang, srl_nokia-platform-linecard-fib.yang, srl_nokia-platform-pipeline-counters.yang, srl_nokia-platform.yang, srl_nokia-policy-types.yang, srl_nokia-protection-policies.yang, srl_nokia-pw-tunnel.yang, srl_nokia-routing-policy.yang, srl_nokia-srv6-types.yang, srl_nokia-srv6.yang, srl_nokia-static-routes@2019-11-30.yang, srl_nokia-system.yang, srl_nokia-traffic-engineering.yang, srl_nokia-tunnel.yang.

    OpenAPI schemas for YANG data models compliant with the NGSI-LD OAS V1.6.1 metamodel according to ETSI GS CIM 009 V1.6.1.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ngsi_ld_models.models.network_instance_protocols_ospf_instance_lsdb_lsa_types_lsa_type_lsas_lsa_opaque_lsa_router_information_tlvs_tlv_informational_capabilities import NetworkInstanceProtocolsOspfInstanceLsdbLsaTypesLsaTypeLsasLsaOpaqueLsaRouterInformationTlvsTlvInformationalCapabilities

class TestNetworkInstanceProtocolsOspfInstanceLsdbLsaTypesLsaTypeLsasLsaOpaqueLsaRouterInformationTlvsTlvInformationalCapabilities(unittest.TestCase):
    """NetworkInstanceProtocolsOspfInstanceLsdbLsaTypesLsaTypeLsasLsaOpaqueLsaRouterInformationTlvsTlvInformationalCapabilities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NetworkInstanceProtocolsOspfInstanceLsdbLsaTypesLsaTypeLsasLsaOpaqueLsaRouterInformationTlvsTlvInformationalCapabilities:
        """Test NetworkInstanceProtocolsOspfInstanceLsdbLsaTypesLsaTypeLsasLsaOpaqueLsaRouterInformationTlvsTlvInformationalCapabilities
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NetworkInstanceProtocolsOspfInstanceLsdbLsaTypesLsaTypeLsasLsaOpaqueLsaRouterInformationTlvsTlvInformationalCapabilities`
        """
        model = NetworkInstanceProtocolsOspfInstanceLsdbLsaTypesLsaTypeLsasLsaOpaqueLsaRouterInformationTlvsTlvInformationalCapabilities()
        if include_optional:
            return NetworkInstanceProtocolsOspfInstanceLsdbLsaTypesLsaTypeLsasLsaOpaqueLsaRouterInformationTlvsTlvInformationalCapabilities(
                id = '',
                type = 'NetworkInstanceProtocolsOspfInstanceLsdbLsaTypesLsaTypeLsasLsaOpaqueLsaRouterInformationTlvsTlvInformationalCapabilities',
                scope = None,
                location = {
                    'key' : null
                    },
                observation_space = {
                    'key' : null
                    },
                operation_space = {
                    'key' : null
                    },
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                modified_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                graceful_restart_capable = None,
                graceful_restart_helper = None,
                stub_router = None,
                point_to_point_over_lan = None,
                experimental_te = None,
                is_part_of = None
            )
        else:
            return NetworkInstanceProtocolsOspfInstanceLsdbLsaTypesLsaTypeLsasLsaOpaqueLsaRouterInformationTlvsTlvInformationalCapabilities(
                type = 'NetworkInstanceProtocolsOspfInstanceLsdbLsaTypesLsaTypeLsasLsaOpaqueLsaRouterInformationTlvsTlvInformationalCapabilities',
                is_part_of = None,
        )
        """

    def testNetworkInstanceProtocolsOspfInstanceLsdbLsaTypesLsaTypeLsasLsaOpaqueLsaRouterInformationTlvsTlvInformationalCapabilities(self):
        """Test NetworkInstanceProtocolsOspfInstanceLsdbLsaTypesLsaTypeLsasLsaOpaqueLsaRouterInformationTlvsTlvInformationalCapabilities"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
