# coding: utf-8

"""
    NGSI-LD API

    ETSI GS CIM 009 V1.6.1 cross-cutting Context Information Management (CIM); NGSI-LD API.

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from ngsi_ld_models.models.retrieve_types200_response import RetrieveTypes200Response  # noqa: E501

class TestRetrieveTypes200Response(unittest.TestCase):
    """RetrieveTypes200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RetrieveTypes200Response:
        """Test RetrieveTypes200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RetrieveTypes200Response`
        """
        model = RetrieveTypes200Response()  # noqa: E501
        if include_optional:
            return RetrieveTypes200Response(
            )
        else:
            return RetrieveTypes200Response(
        )
        """

    def testRetrieveTypes200Response(self):
        """Test RetrieveTypes200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
