# coding: utf-8

"""
    NGSI-LD API

    ETSI GS CIM 009 V1.6.1 cross-cutting Context Information Management (CIM); NGSI-LD API.

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from ngsi_ld_models.models.options_upsert import OptionsUpsert  # noqa: E501

class TestOptionsUpsert(unittest.TestCase):
    """OptionsUpsert unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOptionsUpsert(self):
        """Test OptionsUpsert"""
        # inst = OptionsUpsert()

if __name__ == '__main__':
    unittest.main()
