# coding: utf-8

"""
    NGSI-LD API

    ETSI GS CIM 009 V1.6.1 cross-cutting Context Information Management (CIM); NGSI-LD API.

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from ngsi_ld_models.models.network_link_supporting_link import NetworkLinkSupportingLink  # noqa: E501

class TestNetworkLinkSupportingLink(unittest.TestCase):
    """NetworkLinkSupportingLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NetworkLinkSupportingLink:
        """Test NetworkLinkSupportingLink
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NetworkLinkSupportingLink`
        """
        model = NetworkLinkSupportingLink()  # noqa: E501
        if include_optional:
            return NetworkLinkSupportingLink(
                id = '',
                type = 'NetworkLinkSupportingLink',
                scope = None,
                location = {
                    'key' : null
                    },
                observation_space = {
                    'key' : null
                    },
                operation_space = {
                    'key' : null
                    },
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                modified_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                network_ref = None,
                link_ref = None
            )
        else:
            return NetworkLinkSupportingLink(
                network_ref = None,
                link_ref = None,
        )
        """

    def testNetworkLinkSupportingLink(self):
        """Test NetworkLinkSupportingLink"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
