# coding: utf-8

"""
    NGSI-LD API

    ETSI GS CIM 009 V1.6.1 cross-cutting Context Information Management (CIM); NGSI-LD API.

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from ngsi_ld_models.models.interface_statistics import InterfaceStatistics  # noqa: E501

class TestInterfaceStatistics(unittest.TestCase):
    """InterfaceStatistics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InterfaceStatistics:
        """Test InterfaceStatistics
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InterfaceStatistics`
        """
        model = InterfaceStatistics()  # noqa: E501
        if include_optional:
            return InterfaceStatistics(
                id = '',
                type = 'InterfaceStatistics',
                scope = None,
                location = {
                    'key' : null
                    },
                observation_space = {
                    'key' : null
                    },
                operation_space = {
                    'key' : null
                    },
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                modified_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                is_part_of = None,
                discontinuity_time = None,
                in_octets = None,
                in_unicast_pkts = None,
                in_broadcast_pkts = None,
                in_multicast_pkts = None,
                in_discards = None,
                in_errors = None,
                in_unknown_protos = None,
                out_octets = None,
                out_unicast_pkts = None,
                out_broadcast_pkts = None,
                out_multicast_pkts = None,
                out_discards = None,
                out_errors = None
            )
        else:
            return InterfaceStatistics(
                type = 'InterfaceStatistics',
                is_part_of = None,
                discontinuity_time = None,
        )
        """

    def testInterfaceStatistics(self):
        """Test InterfaceStatistics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
