# coding: utf-8

"""
    NGSI-LD API

    ETSI GS CIM 009 V1.6.1 cross-cutting Context Information Management (CIM); NGSI-LD API.

    The version of the OpenAPI document: 1.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from ngsi_ld_models.models.endpoint import Endpoint
from typing import Optional, Set
from typing_extensions import Self

class NotificationParams(BaseModel):
    """
    5.2.14 represents the parameters that allow to convey the details of a notification. 
    """ # noqa: E501
    attributes: Optional[Annotated[List[StrictStr], Field(min_length=1)]] = Field(default=None, description="Entity Attribute Names (Properties or Relationships) to be included in the notification payload body. If undefined it will mean all Attributes. ")
    sys_attrs: Optional[StrictBool] = Field(default=None, description="If true, the system generated attributes createdAt and modifiedAt are included in the response payload body, in the case of a deletion also deletedAt. ", alias="sysAttrs")
    format: Optional[StrictStr] = Field(default=None, description="Conveys the representation format of the entities delivered at notification time. By default, it will be in the normalized format. ")
    show_changes: Optional[StrictBool] = Field(default=None, description="If true the previous value (previousValue) of Properties or languageMap (previousLanguageMap) of Language Properties or object (previousObject) of Relationships is provided in addition to the current one. This requires that it exists, i.e. in case of modifications and deletions,  but not in the case of creations. showChanges cannot be true in case format is \"keyValues\". ", alias="showChanges")
    endpoint: Endpoint
    status: Optional[StrictStr] = Field(default=None, description="Status of the Notification. It shall be \"ok\" if the last attempt to notify the subscriber succeeded. It shall be \"failed\" if the last attempt to notify the subscriber failed. ")
    times_sent: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="Number of times that the notification has been sent. Provided by the system when querying the details of a subscription. ", alias="timesSent")
    times_failed: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="Number of times an unsuccessful response (or timeout) has been received when deliverying the notification. Provided by the system when querying the details of a subscription. ", alias="timesFailed")
    last_notification: Optional[datetime] = Field(default=None, description="Timestamp corresponding to the instant when the last notification has been sent. Provided by the system when querying the details of a subscription. ", alias="lastNotification")
    last_failure: Optional[datetime] = Field(default=None, description="Timestamp corresponding to the instant when the last notification resulting in failure (for instance, in the HTTP binding, an HTTP response code different than 200) has been sent. Provided by the system when querying the details of a subscription. ", alias="lastFailure")
    last_success: Optional[datetime] = Field(default=None, description="Timestamp corresponding to the instant when the last successful (200 OK response) notification has been sent. Provided by the system when querying the details of a subscription. ", alias="lastSuccess")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["attributes", "sysAttrs", "format", "showChanges", "endpoint", "status", "timesSent", "timesFailed", "lastNotification", "lastFailure", "lastSuccess"]

    @field_validator('format')
    def format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('normalized', 'concise', 'keyValues'):
            raise ValueError("must be one of enum values ('normalized', 'concise', 'keyValues')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('ok', 'failed'):
            raise ValueError("must be one of enum values ('ok', 'failed')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NotificationParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of endpoint
        if self.endpoint:
            _dict['endpoint'] = self.endpoint.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NotificationParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attributes": obj.get("attributes"),
            "sysAttrs": obj.get("sysAttrs"),
            "format": obj.get("format"),
            "showChanges": obj.get("showChanges"),
            "endpoint": Endpoint.from_dict(obj["endpoint"]) if obj.get("endpoint") is not None else None,
            "status": obj.get("status"),
            "timesSent": obj.get("timesSent"),
            "timesFailed": obj.get("timesFailed"),
            "lastNotification": obj.get("lastNotification"),
            "lastFailure": obj.get("lastFailure"),
            "lastSuccess": obj.get("lastSuccess")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


