openapi: 3.0.3
info:
  title: Schemas for model-driven network management protocol clients using data materialization approach
  version: 0.0.1
  description: |
    Schemas for model-driven network management protocol clients using data materialization approach compliant with the NGSI-LD OAS metamodel according to ETSI GS CIM 009.
paths: {}
components:
  schemas:
    Protocol:
      description: | 
        NGSI-LD Entity Type that represents the endpoint of a server supporting a model-driven network management protocol.
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Entity'
        - type: object
          properties:
            type:
              description: NGSI-LD Entity identifier. It has to be Protocol.
              type: string
              enum:
                - Protocol
              default: Protocol
            name:
              $ref: '#/components/schemas/Name'
            address:
              $ref: '#/components/schemas/Address'
            port:
              $ref: '#/components/schemas/Port'
        - required:
            - type
            - address
            - port
    Name:
      description: | 
        NGSI-LD Property Type. The name of the model-driven network management protocol (e.g., NETCONF, gNMI, or RESTCONF).
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Property'
        - type: object
          properties: 
            value:
              type: string
              enum:
                - netconf
                - gnmi
                - restconf
          required:
            - value 
      additionalProperties: false
    Address:
      description: | 
        NGSI-LD Property Type. The hostname or address of the server supporting the model-driven network management protocol.
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Property'
        - type: object
          properties: 
            value:
              type: string
          required:
            - value 
      additionalProperties: false
    Port:
      description: | 
        NGSI-LD Property Type. The port of the server supporting the model-driven network management protocol.
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Property'
        - type: object
          properties: 
            value:
              type: number
          required:
            - value 
      additionalProperties: false
    Credentials:
      description: | 
        NGSI-LD Entity Type that represents the credential of a model-driven network management protocol.
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Entity'
        - type: object
          properties:
            type:
              description: NGSI-LD Entity identifier. It has to be Credentials.
              type: string
              enum:
                - Credentials
              default: Credentials
            username:
              $ref: '#/components/schemas/Username'
            password:
              $ref: '#/components/schemas/Password'
        - required:
            - type
            - username
            - password
    Username:
      description: | 
        NGSI-LD Property Type. The administration username of the NETCONF server.
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Property'
        - type: object
          properties: 
            value:
              type: string
          required:
            - value 
      additionalProperties: false
    Password:
      description: | 
        NGSI-LD Property Type. The administration password of the NETCONF server.
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Property'
        - type: object
          properties: 
            value:
              type: string
          required:
            - value 
      additionalProperties: false
    RpcOperation:
      description: | 
        NGSI-LD Entity Type that represents the template for triggering a Remote Procedure Call (RPC) operation against a network device that supports 
        a model-driven network management protocol.
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Entity'
        - type: object
          properties:
            type:
              description: NGSI-LD Entity identifier. It has to be RpcOperation.
              type: string
              enum:
                - RpcOperation
              default: RpcOperation
            operation:
              $ref: '#/components/schemas/Operation'
        - required:
            - operation
    Operation:
      description: | 
        NGSI-LD Property Type. The NETCONF RPC operation (i.e., GET, SET or SUBSCRIBE).
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Property'
        - type: object
          properties: 
            value:
              type: string
              enum:
                - GET
                - SUBSCRIBE
            getOption:
              $ref: '#/components/schemas/GetOption'
            subscriptionMode:
              $ref: '#/components/schemas/SubscriptionMode'
            subscriptionState:
              $ref: '#/components/schemas/SubscriptionState'
            entityType:
              $ref: '#/components/schemas/NGSILDEntityType'
            entityId:
              $ref: '#/components/schemas/NGSILDEntityId'
          required:
            - value 
      additionalProperties: false
    GetOption:
      description: | 
        NGSI-LD Property Type. The option for the NETCONF RPC GET operation. There are 3 options: 1) 'state' for NETCONF RPC Get operation, 
        2) 'config' for NETCONF RPC Get-Config operation, and 3) 'edit-config' for NETCONF RPC Get-Config operation triggering an 
        NETCONF Set RPC operation.
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Property'
        - type: object
          properties: 
            value:
              type: string
              enum:
                - state
                - config
                - edit-config
          required:
            - value 
      additionalProperties: false
    SubscriptionMode:
      description: | 
        NGSI-LD Property Type. The subscription mode for the NETCONF RPC SUBSCRIBE operation (i.e., on-change or period).
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Property'
        - type: object
          properties: 
            value:
              type: string
              enum:
                - on-change
                - periodic
            period:
              $ref: '#/components/schemas/Period'    
          required:
            - value 
      additionalProperties: false
    SubscriptionState:
      description: | 
        NGSI-LD Property Type. The state for controlling the operation lifecycle for NETCONF RPC SUBSCRIBE operation.
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Property'
        - type: object
          properties: 
            value:
              type: string
              enum:
                - ON
                - IDLE
                - OFF
          required:
            - value 
      additionalProperties: false
    NGSILDEntityType:
      description: | 
        NGSI-LD Property Type. NGSI-LD Entity Type. Both short hand string (type name) or URI are allowed.
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Property'
        - type: object
          properties: 
            value:
              type: string
          required:
            - value 
      additionalProperties: false
    NGSILDEntityId:
      description: | 
        NGSI-LD Property Type. NGSI-LD Entity id.
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Property'
        - type: object
          properties: 
            value:
              type: string
              format: uri
          required:
            - value 
      additionalProperties: false
    Period:
      description: | 
        NGSI-LD Property Type. The period for NETCONF RPC SUBSCRIBE operation there is a periodic subscription.
      allOf:
        - $ref: 'https://raw.githubusercontent.com/giros-dit/python-ngsi-ld-client/1.8.1/schemas/ngsi-ld-api.yaml#/components/schemas/Property'
        - type: object
          properties: 
            value:
              type: number
          required:
            - value 
      additionalProperties: false