# coding: utf-8

"""
    OpenAPI schemas for YANG data models ngsi-ld-api.yaml, ietf-yang-types@2013-07-15.yang, srl_nokia-bridge-table-mac-duplication.yang, srl_nokia-bridge-table-mac-learning.yang, srl_nokia-bridge-table-mac-limit.yang, srl_nokia-bridge-table-shg.yang, srl_nokia-bridge-table.yang, srl_nokia-common.yang, srl_nokia-connection-point-pseudowires.yang, srl_nokia-extensions.yang, srl_nokia-features.yang, srl_nokia-flexible-algorithms-types.yang, srl_nokia-icmp.yang, srl_nokia-if-ip.yang, srl_nokia-interfaces-bridge-table.yang, srl_nokia-interfaces.yang, srl_nokia-ip-route-tables.yang, srl_nokia-isis-lsdb-types.yang, srl_nokia-isis-lsdb.yang, srl_nokia-isis-types.yang, srl_nokia-keychains.yang, srl_nokia-linux@2019-11-30.yang, srl_nokia-lldp-types.yang, srl_nokia-lldp.yang, srl_nokia-load-balancing.yang, srl_nokia-network-instance.yang, srl_nokia-next-hop-groups.yang, srl_nokia-ospf@2020-12-31.yang, srl_nokia-ospf-lsdb.yang, srl_nokia-ospf-types.yang, srl_nokia-ospfv3-lsas.yang, srl_nokia-platform-control-fp.yang, srl_nokia-platform-control.yang, srl_nokia-platform-lc.yang, srl_nokia-platform-linecard-fib.yang, srl_nokia-platform-pipeline-counters.yang, srl_nokia-platform.yang, srl_nokia-policy-types.yang, srl_nokia-protection-policies.yang, srl_nokia-pw-tunnel.yang, srl_nokia-routing-policy.yang, srl_nokia-srv6-types.yang, srl_nokia-srv6.yang, srl_nokia-static-routes@2019-11-30.yang, srl_nokia-system.yang, srl_nokia-tcp-udp.yang, srl_nokia-traffic-engineering.yang, srl_nokia-tunnel.yang.

    OpenAPI schemas for YANG data models compliant with the NGSI-LD OAS V1.6.1 metamodel according to ETSI GS CIM 009 V1.6.1.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from ngsi_ld_models.models.entity_scope import EntityScope
from ngsi_ld_models.models.geo_property import GeoProperty
from ngsi_ld_models.models.linecard_admin_state import LinecardAdminState
from ngsi_ld_models.models.linecard_clei_code import LinecardCleiCode
from ngsi_ld_models.models.linecard_failure_reason import LinecardFailureReason
from ngsi_ld_models.models.linecard_last_booted import LinecardLastBooted
from ngsi_ld_models.models.linecard_last_booted_reason import LinecardLastBootedReason
from ngsi_ld_models.models.linecard_last_change import LinecardLastChange
from ngsi_ld_models.models.linecard_locator_state import LinecardLocatorState
from ngsi_ld_models.models.linecard_manufactured_date import LinecardManufacturedDate
from ngsi_ld_models.models.linecard_oper_state import LinecardOperState
from ngsi_ld_models.models.linecard_part_number import LinecardPartNumber
from ngsi_ld_models.models.linecard_rebooting_at import LinecardRebootingAt
from ngsi_ld_models.models.linecard_removable import LinecardRemovable
from ngsi_ld_models.models.linecard_serial_number import LinecardSerialNumber
from ngsi_ld_models.models.linecard_slot import LinecardSlot
from ngsi_ld_models.models.linecard_software_version import LinecardSoftwareVersion
from ngsi_ld_models.models.linecard_type import LinecardType
from typing import Optional, Set
from typing_extensions import Self

class Linecard(BaseModel):
    """
    Top-level container for linecard configuration and state  YANG module: srl_nokia-platform-lc.yang 
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Entity id. ")
    type: StrictStr = Field(description="NGSI-LD Entity identifier. It has to be Linecard.")
    scope: Optional[EntityScope] = None
    location: Optional[GeoProperty] = None
    observation_space: Optional[GeoProperty] = Field(default=None, alias="observationSpace")
    operation_space: Optional[GeoProperty] = Field(default=None, alias="operationSpace")
    created_at: Optional[datetime] = Field(default=None, description="Is defined as the temporal Property at which the Entity, Property or Relationship was entered into an NGSI-LD system. ", alias="createdAt")
    modified_at: Optional[datetime] = Field(default=None, description="Is defined as the temporal Property at which the Entity, Property or Relationship was last modified in an NGSI-LD system, e.g. in order to correct a previously entered incorrect value. ", alias="modifiedAt")
    deleted_at: Optional[datetime] = Field(default=None, description="Is defined as the temporal Property at which the Entity, Property or Relationship was deleted from an NGSI-LD system.  Entity deletion timestamp. See clause 4.8 It is only used in notifications reporting deletions and in the Temporal Representation of Entities (clause 4.5.6), Properties (clause 4.5.7), Relationships (clause 4.5.8) and LanguageProperties (clause 5.2.32). ", alias="deletedAt")
    slot: Optional[LinecardSlot] = None
    admin_state: Optional[LinecardAdminState] = Field(default=None, alias="adminState")
    oper_state: Optional[LinecardOperState] = Field(default=None, alias="operState")
    last_booted: Optional[LinecardLastBooted] = Field(default=None, alias="lastBooted")
    last_booted_reason: Optional[LinecardLastBootedReason] = Field(default=None, alias="lastBootedReason")
    last_change: Optional[LinecardLastChange] = Field(default=None, alias="lastChange")
    part_number: Optional[LinecardPartNumber] = Field(default=None, alias="partNumber")
    removable: Optional[LinecardRemovable] = None
    failure_reason: Optional[LinecardFailureReason] = Field(default=None, alias="failureReason")
    clei_code: Optional[LinecardCleiCode] = Field(default=None, alias="cleiCode")
    serial_number: Optional[LinecardSerialNumber] = Field(default=None, alias="serialNumber")
    manufactured_date: Optional[LinecardManufacturedDate] = Field(default=None, alias="manufacturedDate")
    rebooting_at: Optional[LinecardRebootingAt] = Field(default=None, alias="rebootingAt")
    linecard_type: Optional[LinecardType] = Field(default=None, alias="linecardType")
    software_version: Optional[LinecardSoftwareVersion] = Field(default=None, alias="softwareVersion")
    locator_state: Optional[LinecardLocatorState] = Field(default=None, alias="locatorState")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "type", "scope", "location", "observationSpace", "operationSpace", "createdAt", "modifiedAt", "deletedAt", "slot", "adminState", "operState", "lastBooted", "lastBootedReason", "lastChange", "partNumber", "removable", "failureReason", "cleiCode", "serialNumber", "manufacturedDate", "rebootingAt", "linecardType", "softwareVersion", "locatorState"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Linecard']):
            raise ValueError("must be one of enum values ('Linecard')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Linecard from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "created_at",
            "modified_at",
            "deleted_at",
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of scope
        if self.scope:
            _dict['scope'] = self.scope.to_dict()
        # override the default output from pydantic by calling `to_dict()` of location
        if self.location:
            _dict['location'] = self.location.to_dict()
        # override the default output from pydantic by calling `to_dict()` of observation_space
        if self.observation_space:
            _dict['observationSpace'] = self.observation_space.to_dict()
        # override the default output from pydantic by calling `to_dict()` of operation_space
        if self.operation_space:
            _dict['operationSpace'] = self.operation_space.to_dict()
        # override the default output from pydantic by calling `to_dict()` of slot
        if self.slot:
            _dict['slot'] = self.slot.to_dict()
        # override the default output from pydantic by calling `to_dict()` of admin_state
        if self.admin_state:
            _dict['adminState'] = self.admin_state.to_dict()
        # override the default output from pydantic by calling `to_dict()` of oper_state
        if self.oper_state:
            _dict['operState'] = self.oper_state.to_dict()
        # override the default output from pydantic by calling `to_dict()` of last_booted
        if self.last_booted:
            _dict['lastBooted'] = self.last_booted.to_dict()
        # override the default output from pydantic by calling `to_dict()` of last_booted_reason
        if self.last_booted_reason:
            _dict['lastBootedReason'] = self.last_booted_reason.to_dict()
        # override the default output from pydantic by calling `to_dict()` of last_change
        if self.last_change:
            _dict['lastChange'] = self.last_change.to_dict()
        # override the default output from pydantic by calling `to_dict()` of part_number
        if self.part_number:
            _dict['partNumber'] = self.part_number.to_dict()
        # override the default output from pydantic by calling `to_dict()` of removable
        if self.removable:
            _dict['removable'] = self.removable.to_dict()
        # override the default output from pydantic by calling `to_dict()` of failure_reason
        if self.failure_reason:
            _dict['failureReason'] = self.failure_reason.to_dict()
        # override the default output from pydantic by calling `to_dict()` of clei_code
        if self.clei_code:
            _dict['cleiCode'] = self.clei_code.to_dict()
        # override the default output from pydantic by calling `to_dict()` of serial_number
        if self.serial_number:
            _dict['serialNumber'] = self.serial_number.to_dict()
        # override the default output from pydantic by calling `to_dict()` of manufactured_date
        if self.manufactured_date:
            _dict['manufacturedDate'] = self.manufactured_date.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rebooting_at
        if self.rebooting_at:
            _dict['rebootingAt'] = self.rebooting_at.to_dict()
        # override the default output from pydantic by calling `to_dict()` of linecard_type
        if self.linecard_type:
            _dict['linecardType'] = self.linecard_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of software_version
        if self.software_version:
            _dict['softwareVersion'] = self.software_version.to_dict()
        # override the default output from pydantic by calling `to_dict()` of locator_state
        if self.locator_state:
            _dict['locatorState'] = self.locator_state.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Linecard from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type") if obj.get("type") is not None else 'Linecard',
            "scope": EntityScope.from_dict(obj["scope"]) if obj.get("scope") is not None else None,
            "location": GeoProperty.from_dict(obj["location"]) if obj.get("location") is not None else None,
            "observationSpace": GeoProperty.from_dict(obj["observationSpace"]) if obj.get("observationSpace") is not None else None,
            "operationSpace": GeoProperty.from_dict(obj["operationSpace"]) if obj.get("operationSpace") is not None else None,
            "createdAt": obj.get("createdAt"),
            "modifiedAt": obj.get("modifiedAt"),
            "deletedAt": obj.get("deletedAt"),
            "slot": LinecardSlot.from_dict(obj["slot"]) if obj.get("slot") is not None else None,
            "adminState": LinecardAdminState.from_dict(obj["adminState"]) if obj.get("adminState") is not None else None,
            "operState": LinecardOperState.from_dict(obj["operState"]) if obj.get("operState") is not None else None,
            "lastBooted": LinecardLastBooted.from_dict(obj["lastBooted"]) if obj.get("lastBooted") is not None else None,
            "lastBootedReason": LinecardLastBootedReason.from_dict(obj["lastBootedReason"]) if obj.get("lastBootedReason") is not None else None,
            "lastChange": LinecardLastChange.from_dict(obj["lastChange"]) if obj.get("lastChange") is not None else None,
            "partNumber": LinecardPartNumber.from_dict(obj["partNumber"]) if obj.get("partNumber") is not None else None,
            "removable": LinecardRemovable.from_dict(obj["removable"]) if obj.get("removable") is not None else None,
            "failureReason": LinecardFailureReason.from_dict(obj["failureReason"]) if obj.get("failureReason") is not None else None,
            "cleiCode": LinecardCleiCode.from_dict(obj["cleiCode"]) if obj.get("cleiCode") is not None else None,
            "serialNumber": LinecardSerialNumber.from_dict(obj["serialNumber"]) if obj.get("serialNumber") is not None else None,
            "manufacturedDate": LinecardManufacturedDate.from_dict(obj["manufacturedDate"]) if obj.get("manufacturedDate") is not None else None,
            "rebootingAt": LinecardRebootingAt.from_dict(obj["rebootingAt"]) if obj.get("rebootingAt") is not None else None,
            "linecardType": LinecardType.from_dict(obj["linecardType"]) if obj.get("linecardType") is not None else None,
            "softwareVersion": LinecardSoftwareVersion.from_dict(obj["softwareVersion"]) if obj.get("softwareVersion") is not None else None,
            "locatorState": LinecardLocatorState.from_dict(obj["locatorState"]) if obj.get("locatorState") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


