# coding: utf-8

"""
    OpenAPI schemas for YANG data models ngsi-ld-api.yaml, ietf-yang-types@2013-07-15.yang, srl_nokia-bridge-table-mac-duplication.yang, srl_nokia-bridge-table-mac-learning.yang, srl_nokia-bridge-table-mac-limit.yang, srl_nokia-bridge-table-shg.yang, srl_nokia-bridge-table.yang, srl_nokia-common.yang, srl_nokia-connection-point-pseudowires.yang, srl_nokia-extensions.yang, srl_nokia-features.yang, srl_nokia-flexible-algorithms-types.yang, srl_nokia-icmp.yang, srl_nokia-if-ip.yang, srl_nokia-interfaces-bridge-table.yang, srl_nokia-interfaces.yang, srl_nokia-ip-route-tables.yang, srl_nokia-isis-lsdb-types.yang, srl_nokia-isis-lsdb.yang, srl_nokia-isis-types.yang, srl_nokia-keychains.yang, srl_nokia-linux@2019-11-30.yang, srl_nokia-lldp-types.yang, srl_nokia-lldp.yang, srl_nokia-load-balancing.yang, srl_nokia-network-instance.yang, srl_nokia-next-hop-groups.yang, srl_nokia-ospf@2020-12-31.yang, srl_nokia-ospf-lsdb.yang, srl_nokia-ospf-types.yang, srl_nokia-ospfv3-lsas.yang, srl_nokia-platform-control-fp.yang, srl_nokia-platform-control.yang, srl_nokia-platform-lc.yang, srl_nokia-platform-linecard-fib.yang, srl_nokia-platform-pipeline-counters.yang, srl_nokia-platform.yang, srl_nokia-policy-types.yang, srl_nokia-protection-policies.yang, srl_nokia-pw-tunnel.yang, srl_nokia-routing-policy.yang, srl_nokia-srv6-types.yang, srl_nokia-srv6.yang, srl_nokia-static-routes@2019-11-30.yang, srl_nokia-system.yang, srl_nokia-tcp-udp.yang, srl_nokia-traffic-engineering.yang, srl_nokia-tunnel.yang.

    OpenAPI schemas for YANG data models compliant with the NGSI-LD OAS V1.6.1 metamodel according to ETSI GS CIM 009 V1.6.1.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from ngsi_ld_models.models.entity_scope import EntityScope
from ngsi_ld_models.models.geo_property import GeoProperty
from ngsi_ld_models.models.is_part_of import IsPartOf
from ngsi_ld_models.models.network_instance_route_table_ipv4_unicast_statistics_active_routes import NetworkInstanceRouteTableIpv4UnicastStatisticsActiveRoutes
from ngsi_ld_models.models.network_instance_route_table_ipv4_unicast_statistics_active_routes_with_ecmp import NetworkInstanceRouteTableIpv4UnicastStatisticsActiveRoutesWithEcmp
from ngsi_ld_models.models.network_instance_route_table_ipv4_unicast_statistics_dynamic_load_balancing_routes import NetworkInstanceRouteTableIpv4UnicastStatisticsDynamicLoadBalancingRoutes
from ngsi_ld_models.models.network_instance_route_table_ipv4_unicast_statistics_fib_failed_routes import NetworkInstanceRouteTableIpv4UnicastStatisticsFibFailedRoutes
from ngsi_ld_models.models.network_instance_route_table_ipv4_unicast_statistics_fib_suppressed_routes import NetworkInstanceRouteTableIpv4UnicastStatisticsFibSuppressedRoutes
from ngsi_ld_models.models.network_instance_route_table_ipv4_unicast_statistics_leaked_routes import NetworkInstanceRouteTableIpv4UnicastStatisticsLeakedRoutes
from ngsi_ld_models.models.network_instance_route_table_ipv4_unicast_statistics_resilient_hash_routes import NetworkInstanceRouteTableIpv4UnicastStatisticsResilientHashRoutes
from ngsi_ld_models.models.network_instance_route_table_ipv4_unicast_statistics_routes_with_per_prefix_statistics import NetworkInstanceRouteTableIpv4UnicastStatisticsRoutesWithPerPrefixStatistics
from ngsi_ld_models.models.network_instance_route_table_ipv4_unicast_statistics_total_routes import NetworkInstanceRouteTableIpv4UnicastStatisticsTotalRoutes
from typing import Optional, Set
from typing_extensions import Self

class NetworkInstanceRouteTableIpv4UnicastStatistics(BaseModel):
    """
     YANG module: srl_nokia-ip-route-tables.yang 
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Entity id. ")
    type: StrictStr = Field(description="NGSI-LD Entity identifier. It has to be NetworkInstanceRouteTableIpv4UnicastStatistics.")
    scope: Optional[EntityScope] = None
    location: Optional[GeoProperty] = None
    observation_space: Optional[GeoProperty] = Field(default=None, alias="observationSpace")
    operation_space: Optional[GeoProperty] = Field(default=None, alias="operationSpace")
    created_at: Optional[datetime] = Field(default=None, description="Is defined as the temporal Property at which the Entity, Property or Relationship was entered into an NGSI-LD system. ", alias="createdAt")
    modified_at: Optional[datetime] = Field(default=None, description="Is defined as the temporal Property at which the Entity, Property or Relationship was last modified in an NGSI-LD system, e.g. in order to correct a previously entered incorrect value. ", alias="modifiedAt")
    deleted_at: Optional[datetime] = Field(default=None, description="Is defined as the temporal Property at which the Entity, Property or Relationship was deleted from an NGSI-LD system.  Entity deletion timestamp. See clause 4.8 It is only used in notifications reporting deletions and in the Temporal Representation of Entities (clause 4.5.6), Properties (clause 4.5.7), Relationships (clause 4.5.8) and LanguageProperties (clause 5.2.32). ", alias="deletedAt")
    active_routes: Optional[NetworkInstanceRouteTableIpv4UnicastStatisticsActiveRoutes] = Field(default=None, alias="activeRoutes")
    active_routes_with_ecmp: Optional[NetworkInstanceRouteTableIpv4UnicastStatisticsActiveRoutesWithEcmp] = Field(default=None, alias="activeRoutesWithEcmp")
    leaked_routes: Optional[NetworkInstanceRouteTableIpv4UnicastStatisticsLeakedRoutes] = Field(default=None, alias="leakedRoutes")
    resilient_hash_routes: Optional[NetworkInstanceRouteTableIpv4UnicastStatisticsResilientHashRoutes] = Field(default=None, alias="resilientHashRoutes")
    dynamic_load_balancing_routes: Optional[NetworkInstanceRouteTableIpv4UnicastStatisticsDynamicLoadBalancingRoutes] = Field(default=None, alias="dynamicLoadBalancingRoutes")
    fib_failed_routes: Optional[NetworkInstanceRouteTableIpv4UnicastStatisticsFibFailedRoutes] = Field(default=None, alias="fibFailedRoutes")
    fib_suppressed_routes: Optional[NetworkInstanceRouteTableIpv4UnicastStatisticsFibSuppressedRoutes] = Field(default=None, alias="fibSuppressedRoutes")
    routes_with_per_prefix_statistics: Optional[NetworkInstanceRouteTableIpv4UnicastStatisticsRoutesWithPerPrefixStatistics] = Field(default=None, alias="routesWithPerPrefixStatistics")
    total_routes: Optional[NetworkInstanceRouteTableIpv4UnicastStatisticsTotalRoutes] = Field(default=None, alias="totalRoutes")
    is_part_of: IsPartOf = Field(alias="isPartOf")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "type", "scope", "location", "observationSpace", "operationSpace", "createdAt", "modifiedAt", "deletedAt", "activeRoutes", "activeRoutesWithEcmp", "leakedRoutes", "resilientHashRoutes", "dynamicLoadBalancingRoutes", "fibFailedRoutes", "fibSuppressedRoutes", "routesWithPerPrefixStatistics", "totalRoutes", "isPartOf"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['NetworkInstanceRouteTableIpv4UnicastStatistics']):
            raise ValueError("must be one of enum values ('NetworkInstanceRouteTableIpv4UnicastStatistics')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NetworkInstanceRouteTableIpv4UnicastStatistics from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "created_at",
            "modified_at",
            "deleted_at",
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of scope
        if self.scope:
            _dict['scope'] = self.scope.to_dict()
        # override the default output from pydantic by calling `to_dict()` of location
        if self.location:
            _dict['location'] = self.location.to_dict()
        # override the default output from pydantic by calling `to_dict()` of observation_space
        if self.observation_space:
            _dict['observationSpace'] = self.observation_space.to_dict()
        # override the default output from pydantic by calling `to_dict()` of operation_space
        if self.operation_space:
            _dict['operationSpace'] = self.operation_space.to_dict()
        # override the default output from pydantic by calling `to_dict()` of active_routes
        if self.active_routes:
            _dict['activeRoutes'] = self.active_routes.to_dict()
        # override the default output from pydantic by calling `to_dict()` of active_routes_with_ecmp
        if self.active_routes_with_ecmp:
            _dict['activeRoutesWithEcmp'] = self.active_routes_with_ecmp.to_dict()
        # override the default output from pydantic by calling `to_dict()` of leaked_routes
        if self.leaked_routes:
            _dict['leakedRoutes'] = self.leaked_routes.to_dict()
        # override the default output from pydantic by calling `to_dict()` of resilient_hash_routes
        if self.resilient_hash_routes:
            _dict['resilientHashRoutes'] = self.resilient_hash_routes.to_dict()
        # override the default output from pydantic by calling `to_dict()` of dynamic_load_balancing_routes
        if self.dynamic_load_balancing_routes:
            _dict['dynamicLoadBalancingRoutes'] = self.dynamic_load_balancing_routes.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fib_failed_routes
        if self.fib_failed_routes:
            _dict['fibFailedRoutes'] = self.fib_failed_routes.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fib_suppressed_routes
        if self.fib_suppressed_routes:
            _dict['fibSuppressedRoutes'] = self.fib_suppressed_routes.to_dict()
        # override the default output from pydantic by calling `to_dict()` of routes_with_per_prefix_statistics
        if self.routes_with_per_prefix_statistics:
            _dict['routesWithPerPrefixStatistics'] = self.routes_with_per_prefix_statistics.to_dict()
        # override the default output from pydantic by calling `to_dict()` of total_routes
        if self.total_routes:
            _dict['totalRoutes'] = self.total_routes.to_dict()
        # override the default output from pydantic by calling `to_dict()` of is_part_of
        if self.is_part_of:
            _dict['isPartOf'] = self.is_part_of.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NetworkInstanceRouteTableIpv4UnicastStatistics from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type") if obj.get("type") is not None else 'NetworkInstanceRouteTableIpv4UnicastStatistics',
            "scope": EntityScope.from_dict(obj["scope"]) if obj.get("scope") is not None else None,
            "location": GeoProperty.from_dict(obj["location"]) if obj.get("location") is not None else None,
            "observationSpace": GeoProperty.from_dict(obj["observationSpace"]) if obj.get("observationSpace") is not None else None,
            "operationSpace": GeoProperty.from_dict(obj["operationSpace"]) if obj.get("operationSpace") is not None else None,
            "createdAt": obj.get("createdAt"),
            "modifiedAt": obj.get("modifiedAt"),
            "deletedAt": obj.get("deletedAt"),
            "activeRoutes": NetworkInstanceRouteTableIpv4UnicastStatisticsActiveRoutes.from_dict(obj["activeRoutes"]) if obj.get("activeRoutes") is not None else None,
            "activeRoutesWithEcmp": NetworkInstanceRouteTableIpv4UnicastStatisticsActiveRoutesWithEcmp.from_dict(obj["activeRoutesWithEcmp"]) if obj.get("activeRoutesWithEcmp") is not None else None,
            "leakedRoutes": NetworkInstanceRouteTableIpv4UnicastStatisticsLeakedRoutes.from_dict(obj["leakedRoutes"]) if obj.get("leakedRoutes") is not None else None,
            "resilientHashRoutes": NetworkInstanceRouteTableIpv4UnicastStatisticsResilientHashRoutes.from_dict(obj["resilientHashRoutes"]) if obj.get("resilientHashRoutes") is not None else None,
            "dynamicLoadBalancingRoutes": NetworkInstanceRouteTableIpv4UnicastStatisticsDynamicLoadBalancingRoutes.from_dict(obj["dynamicLoadBalancingRoutes"]) if obj.get("dynamicLoadBalancingRoutes") is not None else None,
            "fibFailedRoutes": NetworkInstanceRouteTableIpv4UnicastStatisticsFibFailedRoutes.from_dict(obj["fibFailedRoutes"]) if obj.get("fibFailedRoutes") is not None else None,
            "fibSuppressedRoutes": NetworkInstanceRouteTableIpv4UnicastStatisticsFibSuppressedRoutes.from_dict(obj["fibSuppressedRoutes"]) if obj.get("fibSuppressedRoutes") is not None else None,
            "routesWithPerPrefixStatistics": NetworkInstanceRouteTableIpv4UnicastStatisticsRoutesWithPerPrefixStatistics.from_dict(obj["routesWithPerPrefixStatistics"]) if obj.get("routesWithPerPrefixStatistics") is not None else None,
            "totalRoutes": NetworkInstanceRouteTableIpv4UnicastStatisticsTotalRoutes.from_dict(obj["totalRoutes"]) if obj.get("totalRoutes") is not None else None,
            "isPartOf": IsPartOf.from_dict(obj["isPartOf"]) if obj.get("isPartOf") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


