# coding: utf-8

"""
    NGSI-LD OAS

    OpenAPI Specification for NGSI-LD API.

    The version of the OpenAPI document: 1.8.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ngsi_ld_client_1_8_1.models.format_representation import FormatRepresentation

class TestFormatRepresentation(unittest.TestCase):
    """FormatRepresentation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFormatRepresentation(self):
        """Test FormatRepresentation"""
        # inst = FormatRepresentation()

if __name__ == '__main__':
    unittest.main()
