# coding: utf-8

"""
    NGSI-LD OAS

    OpenAPI Specification for NGSI-LD API.

    The version of the OpenAPI document: 1.8.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ngsi_ld_models_1_8_1.models.options_no_overwrite import OptionsNoOverwrite

class TestOptionsNoOverwrite(unittest.TestCase):
    """OptionsNoOverwrite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOptionsNoOverwrite(self):
        """Test OptionsNoOverwrite"""
        # inst = OptionsNoOverwrite()

if __name__ == '__main__':
    unittest.main()
