# coding: utf-8

"""
    NGSI-LD OAS

    OpenAPI Specification for NGSI-LD API.

    The version of the OpenAPI document: 1.8.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ngsi_ld_models_1_8_1.models.retrieve_cs_identity_info200_response import RetrieveCSIdentityInfo200Response

class TestRetrieveCSIdentityInfo200Response(unittest.TestCase):
    """RetrieveCSIdentityInfo200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RetrieveCSIdentityInfo200Response:
        """Test RetrieveCSIdentityInfo200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RetrieveCSIdentityInfo200Response`
        """
        model = RetrieveCSIdentityInfo200Response()
        if include_optional:
            return RetrieveCSIdentityInfo200Response(
                id = '',
                type = 'ContextSourceIdentity',
                context_source_extras = ngsi_ld_models_1_8_1.models.context_source_extras.contextSourceExtras(),
                context_source_up_time = '',
                context_source_time_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                context_source_alias = '0',
                context = None
            )
        else:
            return RetrieveCSIdentityInfo200Response(
                id = '',
                type = 'ContextSourceIdentity',
                context_source_up_time = '',
                context_source_time_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                context_source_alias = '0',
                context = None,
        )
        """

    def testRetrieveCSIdentityInfo200Response(self):
        """Test RetrieveCSIdentityInfo200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
