version: '3.8'
services:
  kafka:
    image: wurstmeister/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_DIRS: "/tmp/kafka-logs"
      KAFKA_CREATE_TOPICS: "interfaces-state-subscriptions:1:1,dictionary-buffers:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    logging:
      driver: none

  zookeeper:
    image: zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181"
    logging:
      driver: none
  
  context-catalog:
    image: halverneus/static-file-server
    hostname: context-catalog
    container_name: context-catalog
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./docker/context-catalog:/web
  
  postgres:
    image: postgis/postgis
    hostname: postgres
    container_name: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
  
  scorpio:
    image: scorpiobroker/all-in-one-runner:java-latest
    hostname: scorpio
    container_name: scorpio
    ports:
      - "9090:9090"
    depends_on:
      - postgres 
  
  notifier-tester:
    build:
      context: .
      dockerfile: ./docker/notifier-tester/Dockerfile
    hostname: notifier-tester
    container_name: notifier-tester
    expose:
      - "8082"
    ports:
      - "8082:8082"
    volumes:
      - ./docker/notifier-tester/notifier_tester:/opt/notifier-tester/notifier_tester
    depends_on:
      - scorpio
      - postgres
      - kafka

  ncclient-collector:
    build:
      context: .
      dockerfile: ./docker/ncclient-collector/Dockerfile
    hostname: ncclient-collector
    container_name: ncclient-collector
    volumes:
      - ./docker/ncclient-collector/ncclient_collector:/opt/ncclient-collector/ncclient_collector
    depends_on:
      - kafka
