# coding: utf-8

"""
    OpenAPI schemas for YANG data models ietf-interfaces@2018-02-20.yang, ietf-yang-types@2023-01-23.yang, ietf-ip@2018-02-22.yang, ietf-inet-types@2013-07-15.yang, iana-if-type@2014-05-08.yang.

    OpenAPI schemas for YANG data models compliant with the NGSI-LD OAS V1.6.1 metamodel according to ETSI GS CIM 009 V1.6.1.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ngsi_ld_models.models.geometry_multi_polygon import GeometryMultiPolygon

class TestGeometryMultiPolygon(unittest.TestCase):
    """GeometryMultiPolygon unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeometryMultiPolygon:
        """Test GeometryMultiPolygon
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeometryMultiPolygon`
        """
        model = GeometryMultiPolygon()
        if include_optional:
            return GeometryMultiPolygon(
                type = 'MultiPolygon',
                coordinates = [
                    ngsi_ld_models.models.geometry/line_string.Geometry.LineString(
                        type = 'LineString', )
                    ]
            )
        else:
            return GeometryMultiPolygon(
        )
        """

    def testGeometryMultiPolygon(self):
        """Test GeometryMultiPolygon"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
