services:
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181"
    logging:
      driver: none

  kafka:
    image: bitnami/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_MS: 10000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    logging:
      driver: none
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  context-catalog:
    image: halverneus/static-file-server
    hostname: context-catalog
    container_name: context-catalog
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./docker/context-catalog:/web

  postgres:
    image: postgis/postgis
    hostname: postgres
    container_name: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "ngb", "-U", "ngb"]
      interval: 10s
      timeout: 5s
      retries: 5

  scorpio:
    image: scorpiobroker/all-in-one-runner:java-latest
    hostname: scorpio
    container_name: scorpio
    expose:
      - "9090"
    ports:
      - "9090:9090"
    depends_on:
      postgres:
        condition: service_healthy
      context-catalog:
        condition: service_started

  notifier-tester:
    build:
      context: .
      dockerfile: ./docker/notifier-tester/Dockerfile
    image: testbeds-netconf-notifier-tester:latest
    hostname: notifier-tester
    container_name: notifier-tester
    expose:
      - "8082"
    ports:
      - "8082:8082"
    volumes:
      - ./docker/notifier-tester/notifier_tester:/opt/notifier-tester/notifier_tester
    depends_on:
      scorpio:
        condition: service_started
      context-catalog:
        condition: service_started
      kafka:
        condition: service_started
    restart: always
  
  ncclient-collector-builder:
    image: testbeds-netconf-ncclient-collector:latest
    command: ["echo", "Build completed"]
    build:
      context: ./docker/ncclient-collector/
      dockerfile: Dockerfile

  ncclient-collector-1:
    image: testbeds-netconf-ncclient-collector:latest
    hostname: ncclient-collector-1
    container_name: ncclient-collector-1
    command: ["python3", "-u", "/opt/ncclient-collector/ncclient-collector-kafka.py", "clab-telemetry-ixiac-lab-r1", "GigabitEthernet2", "6000"]
    volumes:
      - ./docker/ncclient-collector:/opt/ncclient-collector
    depends_on:
      ncclient-collector-builder:
        condition: service_completed_successfully
      kafka:
        condition: service_started

  ncclient-collector-2:
    image: testbeds-netconf-ncclient-collector:latest
    hostname: ncclient-collector-2
    container_name: ncclient-collector-2
    command: ["python3", "-u", "/opt/ncclient-collector/ncclient-collector-kafka.py", "clab-telemetry-ixiac-lab-r1", "GigabitEthernet3", "6000"]
    volumes:
      - ./docker/ncclient-collector:/opt/ncclient-collector
    depends_on:
      ncclient-collector-builder:
        condition: service_completed_successfully
      kafka:
        condition: service_started

  ncclient-collector-3:
    image: testbeds-netconf-ncclient-collector:latest
    hostname: ncclient-collector-3
    container_name: ncclient-collector-3
    command: ["python3", "-u", "/opt/ncclient-collector/ncclient-collector-kafka.py", "clab-telemetry-ixiac-lab-r2", "GigabitEthernet2", "6000"]
    volumes:
      - ./docker/ncclient-collector:/opt/ncclient-collector
    depends_on:
      ncclient-collector-builder:
        condition: service_completed_successfully
      kafka:
        condition: service_started

  ncclient-collector-4:
    image: testbeds-netconf-ncclient-collector:latest
    hostname: ncclient-collector-4
    container_name: ncclient-collector-4
    command: ["python3", "-u", "/opt/ncclient-collector/ncclient-collector-kafka.py", "clab-telemetry-ixiac-lab-r2", "GigabitEthernet3", "6000"]
    volumes:
      - ./docker/ncclient-collector:/opt/ncclient-collector
    depends_on:
      ncclient-collector-builder:
        condition: service_completed_successfully
      kafka:
        condition: service_started

  xml-parser-with-ngsi-ld-instantiator:
    build:
      context: .
      dockerfile: ./docker/xml-parser-with-ngsi-ld-instantiator/Dockerfile
    image: testbeds-netconf-xml-parser-with-ngsi-ld-instantiator:latest
    hostname: xml-parser-with-ngsi-ld-instantiator
    container_name: xml-parser-with-ngsi-ld-instantiator
    volumes:
      - ./docker/xml-parser-with-ngsi-ld-instantiator:/opt/xml-parser-with-ngsi-ld-instantiator
    depends_on:
      scorpio:
        condition: service_started
      context-catalog:
        condition: service_started
      kafka:
        condition: service_started
    restart: always

networks:
  default:
    name: clab
    external: true
