services:
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181"
    logging:
      driver: none

  kafka:
    image: wurstmeister/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_DIRS: "/tmp/kafka-logs"
      KAFKA_CREATE_TOPICS: "interfaces-state-subscriptions:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    logging:
      driver: none
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  context-catalog:
    image: halverneus/static-file-server
    hostname: context-catalog
    container_name: context-catalog
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./docker/context-catalog:/web

  orion:
    image: fiware/orion-ld
    hostname: orion
    container_name: fiware-orion
    expose:
      - "1026"
    ports:
      - "1026:1026"
    depends_on:
      - mongo-db
      - context-catalog
    command: -dbhost mongo-db -logLevel DEBUG

  mongo-db:
    image: mongo:3.6
    hostname: mongo-db
    container_name: mongo-db
    ports:
      - "27017:27017" 
    networks:
      - default
    command: --nojournal
    volumes:
      - mongo-db:/data
  
  xml-parser-with-ngsi-ld-instantiator:
    build:
      context: .
      dockerfile: ./docker/xml-parser-with-ngsi-ld-instantiator-throughput-translation/Dockerfile
    image: testbeds-netconf-xml-parser-with-ngsi-ld-instantiator:latest
    hostname: xml-parser-with-ngsi-ld-instantiator
    container_name: xml-parser-with-ngsi-ld-instantiator
    volumes:
      - ./docker/xml-parser-with-ngsi-ld-instantiator-throughput-translation:/opt/xml-parser-with-ngsi-ld-instantiator
    healthcheck:
      test: ["CMD", "python3", "--version"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      orion:
        condition: service_started
      context-catalog:
        condition: service_started
      kafka:
        condition: service_healthy
    restart: always

  fake-ncclient-collector:
    build:
      context: ./docker/fake-ncclient-collector-throughput/
      dockerfile: Dockerfile
    hostname: fake-ncclient-collector
    container_name: fake-ncclient-collector
    command: ["python3", "-u", "/opt/fake-ncclient-collector/ncclient-collector-kafka-all-throughput.py", "clab-telemetry-ixiac-lab-r1"]
    volumes:
      - ./docker/fake-ncclient-collector-throughput:/opt/fake-ncclient-collector
    depends_on:
      xml-parser-with-ngsi-ld-instantiator:
        condition: service_healthy
      kafka:
        condition: service_healthy
volumes:
  mongo-db: ~