services:
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181"
    logging:
      driver: none

  kafka:
    image: wurstmeister/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_DIRS: "/tmp/kafka-logs"
      KAFKA_CREATE_TOPICS: "interfaces-state-subscriptions:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    logging:
      driver: none
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  context-catalog:
    image: halverneus/static-file-server
    hostname: context-catalog
    container_name: context-catalog
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./docker/context-catalog:/web

  postgres:
    image: postgis/postgis
    hostname: postgres
    container_name: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "ngb", "-U", "ngb"]
      interval: 10s
      timeout: 5s
      retries: 5

  scorpio:
    image: scorpiobroker/all-in-one-runner:java-latest
    hostname: scorpio
    container_name: scorpio
    expose:
      - "9090"
    ports:
      - "9090:9090"
    depends_on:
      postgres:
        condition: service_healthy
      context-catalog:
        condition: service_started

  notifier-tester-materialization-on-change:
    build:
      context: .
      dockerfile: ./docker/notifier-tester-materialization-on-change/Dockerfile
    hostname: notifier-tester-materialization-on-change
    container_name: notifier-tester-materialization-on-change
    expose:
      - "8082"
    ports:
      - "8082:8082"
    volumes:
      - ./docker/notifier-tester-materialization-on-change/notifier_tester_materialization_on_change:/opt/notifier-tester-materialization-on-change/notifier_tester_materialization_on_change
    depends_on:
      scorpio:
        condition: service_started
      context-catalog:
        condition: service_started
      kafka:
        condition: service_started
    restart: always

  network-controller-materialization:
    build:
      context: .
      dockerfile: ./docker/network-controller-materialization/Dockerfile
    hostname: network-controller-materialization
    container_name: network-controller-materialization
    expose:
      - "8089"
    ports:
      - "8089:8089"
    volumes:
      - ./docker/network-controller-materialization/network_controller_materialization:/opt/network-controller-materialization/network_controller_materialization
    depends_on:
      scorpio:
        condition: service_started
      context-catalog:
        condition: service_started
      kafka:
        condition: service_started
    restart: always

  xml-parser-with-ngsi-ld-instantiator-materialization:
    build:
      context: .
      dockerfile: ./docker/xml-parser-with-ngsi-ld-instantiator-materialization/Dockerfile
    hostname: xml-parser-with-ngsi-ld-instantiator-materialization
    container_name: xml-parser-with-ngsi-ld-instantiator-materialization
    volumes:
      - ./docker/xml-parser-with-ngsi-ld-instantiator-materialization:/opt/xml-parser-with-ngsi-ld-instantiator-materialization
    depends_on:
      scorpio:
        condition: service_started
      context-catalog:
        condition: service_started
      kafka:
        condition: service_healthy
    restart: always
    
  query-tester-materialization-context-broker:
    build:
      context: .
      dockerfile: ./docker/query-tester-materialization-context-broker/Dockerfile
    hostname: query-tester-materialization-context-broker
    container_name: query-tester-materialization-context-broker
    expose:
      - "8083"
    ports:
      - "8083:8083"
    volumes:
      - ./docker/query-tester-materialization-context-broker/query_tester_materialization_context_broker:/opt/query-tester-materialization-context-broker/query_tester_materialization_context_broker
    depends_on:
      scorpio:
        condition: service_started
      context-catalog:
        condition: service_started
      kafka:
        condition: service_started
      network-controller-materialization:
        condition: service_started
    restart: always

  ngsi-ld-cleaner:
    build:
      context: .
      dockerfile: ./docker/ngsi-ld-cleaner/Dockerfile
    hostname: ngsi-ld-cleaner
    container_name: ngsi-ld-cleaner
    command: ["poetry", "run", "python", "-u", "ngsi_ld_cleaner.py", "1"]
    volumes:
      - ./docker/ngsi-ld-cleaner:/opt/ngsi-ld-cleaner
    depends_on:
      scorpio:
        condition: service_started
      context-catalog:
        condition: service_started
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      xml-parser-with-ngsi-ld-instantiator-materialization:
        condition: service_started
    restart: always

networks:
  default:
    name: clab
    external: true
