services:
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181"
    logging:
      driver: none

  kafka:
    image: wurstmeister/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_DIRS: "/tmp/kafka-logs"
      KAFKA_CREATE_TOPICS: "interfaces-state-subscriptions:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    logging:
      driver: none
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  context-catalog:
    image: halverneus/static-file-server
    hostname: context-catalog
    container_name: context-catalog
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./docker/context-catalog:/web

  postgres:
    image: postgis/postgis
    hostname: postgres
    container_name: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "ngb", "-U", "ngb"]
      interval: 10s
      timeout: 5s
      retries: 5

  scorpio:
    image: scorpiobroker/all-in-one-runner:java-latest
    hostname: scorpio
    container_name: scorpio
    expose:
      - "9090"
    ports:
      - "9090:9090"
    depends_on:
      postgres:
        condition: service_healthy
      context-catalog:
        condition: service_started

  notifier-tester:
    build:
      context: .
      dockerfile: ./docker/notifier-tester/Dockerfile
    image: testbeds-netconf-notifier-tester:latest
    hostname: notifier-tester
    container_name: notifier-tester
    expose:
      - "8082"
    ports:
      - "8082:8082"
    volumes:
      - ./docker/notifier-tester/notifier_tester:/opt/notifier-tester/notifier_tester
    depends_on:
      scorpio:
        condition: service_started
      context-catalog:
        condition: service_started
      kafka:
        condition: service_healthy
    restart: always
  
  xml-parser-with-ngsi-ld-instantiator:
    build:
      context: .
      dockerfile: ./docker/xml-parser-with-ngsi-ld-instantiator/Dockerfile
    image: testbeds-netconf-xml-parser-with-ngsi-ld-instantiator:latest
    hostname: xml-parser-with-ngsi-ld-instantiator
    container_name: xml-parser-with-ngsi-ld-instantiator
    volumes:
      - ./docker/xml-parser-with-ngsi-ld-instantiator:/opt/xml-parser-with-ngsi-ld-instantiator
    depends_on:
      scorpio:
        condition: service_started
      context-catalog:
        condition: service_started
      kafka:
        condition: service_healthy
    restart: always

  fake-ncclient-collector:
    build:
      context: ./docker/fake-ncclient-collector/
      dockerfile: Dockerfile
    hostname: fake-ncclient-collector
    container_name: fake-ncclient-collector
    command: ["python3", "-u", "/opt/fake-ncclient-collector/ncclient-collector-kafka.py", "clab-telemetry-ixiac-lab-r1", "1"]
    volumes:
      - ./docker/fake-ncclient-collector:/opt/fake-ncclient-collector
    depends_on:
      xml-parser-with-ngsi-ld-instantiator:
        condition: service_started
      kafka:
        condition: service_healthy