services:
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181"
    logging:
      driver: none

  kafka:
    image: wurstmeister/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_DIRS: "/tmp/kafka-logs"
      KAFKA_CREATE_TOPICS: "interfaces-state-subscriptions:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    logging:
      driver: none
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  context-catalog:
    image: halverneus/static-file-server
    hostname: context-catalog
    container_name: context-catalog
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./docker/context-catalog:/web

  postgres:
    image: postgis/postgis
    hostname: postgres
    container_name: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "ngb", "-U", "ngb"]
      interval: 10s
      timeout: 5s
      retries: 5

  scorpio:
    image: scorpiobroker/all-in-one-runner:java-latest
    hostname: scorpio
    container_name: scorpio
    expose:
      - "9090"
    ports:
      - "9090:9090"
    depends_on:
      postgres:
        condition: service_healthy
      context-catalog:
        condition: service_started

  netconf-notifier-tester-virtualization-on-change:
    build:
      context: .
      dockerfile: ./docker/netconf-notifier-tester-virtualization-on-change-context-source/Dockerfile
    hostname: netconf-notifier-tester-virtualization-on-change
    container_name: netconf-notifier-tester-virtualization-on-change
    expose:
      - "8082"
    ports:
      - "8082:8082"
    volumes:
      - ./docker/netconf-notifier-tester-virtualization-on-change-context-source/netconf_notifier_tester_virtualization_on_change_context_source:/opt/netconf-notifier-tester-virtualization-on-change-context-source/netconf_notifier_tester_virtualization_on_change_context_source
    depends_on:
      scorpio:
        condition: service_started
      context-catalog:
        condition: service_started
      kafka:
        condition: service_started
      netconf-xml-parser-with-ngsi-ld-instantiator-virtualization:
        condition: service_healthy
      netconf-network-controller-virtualization:
        condition: service_healthy
    restart: always

  netconf-network-controller-virtualization:
    build:
      context: .
      dockerfile: ./docker/netconf-network-controller-virtualization/Dockerfile
    hostname: netconf-network-controller-virtualization
    container_name: netconf-network-controller-virtualization
    expose:
      - "8089"
    ports:
      - "8089:8089"
    volumes:
      - ./docker/netconf-network-controller-virtualization/netconf_network_controller_virtualization:/opt/netconf-network-controller-virtualization/netconf_network_controller_virtualization
    healthcheck:
      test: ["CMD", "python3", "--version"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      scorpio:
        condition: service_started
      context-catalog:
        condition: service_started
      kafka:
        condition: service_started
    restart: always

  netconf-xml-parser-with-ngsi-ld-instantiator-virtualization:
    build:
      context: .
      dockerfile: ./docker/netconf-xml-parser-with-ngsi-ld-instantiator-virtualization/Dockerfile
    hostname: netconf-xml-parser-with-ngsi-ld-instantiator-virtualization
    container_name: netconf-xml-parser-with-ngsi-ld-instantiator-virtualization
    volumes:
      - ./docker/netconf-xml-parser-with-ngsi-ld-instantiator-virtualization:/opt/netconf-xml-parser-with-ngsi-ld-instantiator-virtualization
    healthcheck:
      test: ["CMD", "python3", "--version"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      scorpio:
        condition: service_started
      context-catalog:
        condition: service_started
      kafka:
        condition: service_healthy
    restart: always

networks:
  default:
    name: clab
    external: true
