targets:
  ceos1:
    # gNMI target address; CLI flag `--address`
    address: "clab-telemetry-testbed-ceos-ceos-4hosts-r1:6030"
    # gNMI target user name; CLI flag `--username`
    username: admin
    # gNMI target user password; CLI flag `--password`
    password: admin
    # connection mode; CLI flag `--insecure`
    insecure: true
    # log file location; CLI flag `--log-file`
    log-file: /tmp/gnmic-1.log
    subscriptions:
      - ceos1_traffic_stats
      - ceos1_port_stats
  ceos2:
    # gNMI target address; CLI flag `--address`
    address: "clab-telemetry-testbed-ceos-ceos-4hosts-r2:6030"
    # gNMI target user name; CLI flag `--username`
    username: admin
    # gNMI target user password; CLI flag `--password`
    password: admin
    # connection mode; CLI flag `--insecure`
    insecure: true
    # log file location; CLI flag `--log-file`
    log-file: /tmp/gnmic-2.log
    subscriptions:
      - ceos2_traffic_stats
      - ceos2_port_stats
subscriptions:
  ceos1_traffic_stats:
    paths:
    #  - "/interfaces/interface[name=Ethernet1]/state/counters"
      - "/interfaces/interface[name=Ethernet1]/state/counters/in-octets"
    #  - "/interfaces/interface[name=Ethernet1]/state/counters/in-pkts"
    #  - "/interfaces/interface[name=Ethernet1]/state/counters/out-octets"
    #  - "/interfaces/interface[name=Ethernet1]/state/counters/out-pkts"
    stream-mode: sample
    sample-interval: 5s
    encoding: JSON_IETF
    outputs: 
      - output1-ceos1
  ceos1_port_stats:
    paths:
      - "/interfaces/interface[name=Ethernet1]/state/admin-status"
      - "/interfaces/interface[name=Ethernet1]/state/oper-status"
    stream-mode: on-change
    encoding: JSON_IETF
    outputs: 
      - output2-ceos1
  ceos2_traffic_stats:
    paths:
    #  - "/interfaces/interface[name=Ethernet1]/state/counters"
      - "/interfaces/interface[name=Ethernet1]/state/counters/in-octets"
    #  - "/interfaces/interface[name=Ethernet1]/state/counters/in-pkts"
    #  - "/interfaces/interface[name=Ethernet1]/state/counters/out-octets"
    #  - "/interfaces/interface[name=Ethernet1]/state/counters/out-pkts"
    stream-mode: sample
    sample-interval: 5s
    encoding: JSON_IETF
    outputs: 
      - output1-ceos2
  ceos2_port_stats:
    paths:
      - "/interfaces/interface[name=Ethernet1]/state/admin-status"
      - "/interfaces/interface[name=Ethernet1]/state/oper-status"
    stream-mode: on-change
    encoding: JSON_IETF
    outputs: 
      - output2-ceos2
outputs:
  output1-ceos1:
    # required
    type: kafka
    # Comma separated brokers addresses
    address: kafka:9092
    # Kafka topic name
    topic: interfaces-state-notifications
    max-retry: 2
    # Kafka connection timeout
    timeout: 5s
    # Wait time to reestablish the kafka producer connection after a failure
    recovery-wait-time: 10s
    # Exported msg format, json, protojson, prototext, proto, event
    format: event
    #event-processors:
    #  - group-by-processor
    #  - merge-processor
  output2-ceos1:
    # required
    type: kafka
    # Comma separated brokers addresses
    address: kafka:9092
    # Kafka topic name
    topic: interfaces-oper-notifications
    max-retry: 2
    # Kafka connection timeout
    timeout: 5s
    # Wait time to reestablish the kafka producer connection after a failure
    recovery-wait-time: 10s
    # Exported msg format, json, protojson, prototext, proto, event
    format: event
  output1-ceos2:
    # required
    type: kafka
    # Comma separated brokers addresses
    address: kafka:9092
    # Kafka topic name
    topic: interfaces-state-notifications
    max-retry: 2
    # Kafka connection timeout
    timeout: 5s
    # Wait time to reestablish the kafka producer connection after a failure
    recovery-wait-time: 10s
    # Exported msg format, json, protojson, prototext, proto, event
    format: event
    #event-processors:
    #  - group-by-processor
    #  - merge-processor
  output2-ceos2:
    # required
    type: kafka
    # Comma separated brokers addresses
    address: kafka:9092
    # Kafka topic name
    topic: interfaces-oper-notifications
    max-retry: 2
    # Kafka connection timeout
    timeout: 5s
    # Wait time to reestablish the kafka producer connection after a failure
    recovery-wait-time: 10s
    # Exported msg format, json, protojson, prototext, proto, event
    format: event
      
processors:
  # processor name
  group-by-processor:
    # processor type
    event-group-by:
      tags:
        - source
  # processor name
  merge-processor:
    # processor type
    event-merge:
      # if always is set to true, 
      # the updates are merged regardless of the timestamp values
      always: true
      debug: false