# coding: utf-8

"""
    Schemas for model-driven network management protocol clients using data virtualization approach

    Schemas for model-driven network management protocol clients using data virtualization approach compliant with the NGSI-LD OAS metamodel according to ETSI GS CIM 009. 

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ngsi_ld_models_mdt_client_data_virtualization.models.geometry_point import GeometryPoint

class TestGeometryPoint(unittest.TestCase):
    """GeometryPoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeometryPoint:
        """Test GeometryPoint
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeometryPoint`
        """
        model = GeometryPoint()
        if include_optional:
            return GeometryPoint(
                type = 'Point',
                coordinates = [
                    1.337
                    ]
            )
        else:
            return GeometryPoint(
        )
        """

    def testGeometryPoint(self):
        """Test GeometryPoint"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
